import 'model/fabric.dart';
import 'model/order.dart';
import 'model/client.dart';

List<Client> testClients = [
  Client(
    name: '',
    surname: 'Колумб',
    middleName: '',
    city: 'Генуя',
    address: 'ул. Красная, д.137, кв. 381',
    volume: '',
    previousDate: '12.02.1466',
    nextDate: '',
    //'images':'',
  ),
  Client(
    name: 'Исаак',
    surname: 'Ньютон',
    middleName: '',
    city: 'Вулсторп',
    address: '',
    volume: '20',
    previousDate: '24.09.1689',
    nextDate: '',
    //images:'',
  ),
  Client(
    name: 'Луи',
    surname: 'Пастер',
    middleName: '',
    city: 'Доль',
    address: '',
    volume: '',
    previousDate: '',
    nextDate: '',
    //images:'',
  ),
  Client(
    name: 'Джеймс',
    surname: 'Максвелл',
    middleName: 'Клерк',
    city: 'Эдинбург',
    address: '',
    volume: '10',
    previousDate: '07.03.1844',
    nextDate: '',
    //images:'',
  ),
  Client(
    name: 'Джон',
    surname: 'Дальтон',
    middleName: '',
    city: 'Иглсфилд',
    address: '',
    volume: '13',
    previousDate: '',
    nextDate: '',
    //images:'',
  ),
  Client(
    name: '',
    surname: 'Колумб',
    middleName: '',
    city: 'Генуя',
    address: 'ул. Красная, д.137, кв. 381',
    volume: '',
    previousDate: '12.02.1466',
    nextDate: '',
    //'images':'',
  ),
  Client(
    name: 'Исаак',
    surname: 'Ньютон',
    middleName: '',
    city: 'Вулсторп',
    address: '',
    volume: '20',
    previousDate: '24.09.1689',
    nextDate: '',
    //images:'',
  ),
  Client(
    name: 'Луи',
    surname: 'Пастер',
    middleName: '',
    city: 'Доль',
    address: '',
    volume: '',
    previousDate: '',
    nextDate: '',
    //images:'',
  ),
  Client(
    name: 'Джеймс',
    surname: 'Максвелл',
    middleName: 'Клерк',
    city: 'Эдинбург',
    address: '',
    volume: '10',
    previousDate: '07.03.1844',
    nextDate: '',
    //images:'',
  ),
  Client(
    name: 'Джон',
    surname: 'Дальтон',
    middleName: '',
    city: 'Иглсфилд',
    address: '',
    volume: '13',
    previousDate: '',
    nextDate: '',
    //images:'',
  ),
];

List<Order> testOrders = [
  Order(
    client: testClients[0],
    date: '21.02.12',
    done: false,
    price: 1000,
    expenses: 250,
    comment: 'dsadasdsadasda dsadasdsadasda dsadasdsadasda dsadasdsadasda dsadasdsadasda dsadasdsadasda dsadasdsadasda dsadasdsadasdadsadasdsadasdadsadasdsadasdadsadasdsadasdadsadasdsadasdadsadasdsadasda  dsadasdsadasda dsadasdsadasdadsadasdsadasda dsadasdsadasdav',
  ),
  Order(
    client: testClients[1],
    date: '21.07.05',
    comment: 'dsadasdsadasda dsadasdsadasda dsadasdsadasda dsadasdsadasda dsadasdsadasda dsadasdsadasda dsadasdsadasda dsadasdsadasdadsadasdsadasdadsadasdsadasdadsadasdsadasdadsadasdsadasdadsadasdsadasda  dsadasdsadasda dsadasdsadasdadsadasdsadasda dsadasdsadasdav',
  ),
  Order(
    client: testClients[2],
    date: '12.02.05',
    done: true,
    comment: 'dsadasdsadasda dsadasdsadasda dsadasdsadasda dsadasdsadasda dsadasdsadasda dsadasdsadasda dsadasdsadasda dsadasdsadasdadsadasdsadasdadsadasdsadasdadsadasdsadasdadsadasdsadasdadsadasdsadasda  dsadasdsadasda dsadasdsadasdadsadasdsadasda dsadasdsadasdav',
  ),
  Order(
    client: testClients[3],
    date: '21.09.17',
  ),
  Order(
    client: testClients[0],
    date: '21.02.12',
    done: true,
    comment: 'dsadasdsadasda dsadasdsadasda dsadasdsadasda dsadasdsadasda dsadasdsadasda dsadasdsadasda dsadasdsadasda dsadasdsadasdadsadasdsadasdadsadasdsadasdadsadasdsadasdadsadasdsadasdadsadasdsadasda  dsadasdsadasda dsadasdsadasdadsadasdsadasda dsadasdsadasdav',
  ),Order(
    client: testClients[0],
    date: '21.02.12',
    done: true,
  ),
  Order(
    client: testClients[1],
    date: '21.07.05',
  ),
  Order(
    client: testClients[2],
    date: '21.02.12',
    done: true,
    comment: 'dsadasdsadasda dsadasdsadasda dsadasdsadasda dsadasdsadasda dsadasdsadasda dsadasdsadasda dsadasdsadasda dsadasdsadasdadsadasdsadasdadsadasdsadasdadsadasdsadasdadsadasdsadasdadsadasdsadasda  dsadasdsadasda dsadasdsadasdadsadasdsadasda dsadasdsadasdav',
  ),
  Order(
    client: testClients[3],
    date: '21.09.17',
  ),
  Order(
    client: testClients[0],
    date: '21.02.12',
    done: true,
  ),
];

List<Fabric> testFabrics = [
  Fabric(title: 'Дерево'),
  Fabric(title: 'Металл'),
  Fabric(title: 'Стекло'),
  Fabric(title: 'Пластмасса'),
  Fabric(title: 'Дерево'),
  Fabric(title: 'Металл'),
  Fabric(title: 'Стекло'),
  Fabric(title: 'Пластмасса'),
  Fabric(title: 'Дерево'),
  Fabric(title: 'Металл'),
  Fabric(title: 'Стекло'),
  Fabric(title: 'Пластмасса'),
];